dataset:
  name: wood
  num_classes: 130
  image_size: 224
  pre_size: 256

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ../OOD_wood/
    imglist_pth: ./data/benchmark_imglist/wood/train_wood.txt
    batch_size: 64
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ../OOD_wood/
    imglist_pth: ./data/benchmark_imglist/wood/test_wood.txt
    batch_size: 64
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ../OOD_wood/
    imglist_pth: ./data/benchmark_imglist/wood/test_wood.txt
    batch_size: 64
    shuffle: False
